apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 4.5.0
    helm:
      values: |
        installCRDs: false
        server:
          service:
            type: NodePort
          ingress:
            enabled: false
          rbacConfig:
            "policy.default": role:readonly
    chart: argo-cd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
