apiVersion: v1
kind: Service
metadata:
  namespace: sidekiq
  name: sidekiq-exporter
  labels:
    app: sidekiq-exporter
spec:
  selector:
    app: sidekiq-exporter
  ports:
  - port: 9292
    name: exporter
