apiVersion: v1
kind: Service
metadata:
  name: sidekiq-exporter
  namespace: sidekiq
  labels:
    app: sidekiq-exporter
spec:
  selector:
    app: sidekiq-exporter
  ports:
  - port: 9292
    name: exporter
