kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
  labels:
data:
  # Ref: https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/fargate-logging.html
  output.conf: |
    [OUTPUT]
      Name  kinesis_firehose
      Match kube.var.log.containers.nginx-*_nginx_nginx-*.log
      region ap-northeast-1
      delivery_stream nginx_nginx

  filters.conf: |
    [FILTER]
        Name             kubernetes
        Match            kube.*
        Merge_Log           On
        Buffer_Size         0
        Kube_Meta_Cache_TTL 300s
        
    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes_

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes_labels
        Add_prefix kubernetes_labels_

    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes_annotations
        Add_prefix kubernetes_annotations_
