apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.3.8
    helm:
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          # oidcのiam-roleにsecrets-managerの権限付与(irsa.tf)
          value: "arn:aws:iam::009554248005:role/oidc-external-secrets"
      values: |
        serviceAccount:
          name: "external-secrets"
        env:
          AWS_REGION: "ap-northeast-1"
    chart: external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
