apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent-for-sidecar
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - nodes/pods
      - nodes/healthz
    verbs:
      - get
      - list
      - watch
  # ?
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
      - events
      - endpoints
      - pods
      - nodes
      - componentstatuses
      # ?
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["quota.openshift.io"]
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - datadogtoken
      - datadog-leader-election
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - nonResourceURLs:
    - "/version"
    - "/healthz"
    - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent-for-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent-for-sidecar
subjects:
  - kind: ServiceAccount
    name: go-app
    namespace: go-app
