kind: Namespace
apiVersion: v1
metadata:
  name: go
  labels:
    name: go
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go
  namespace: go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  namespace: go
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go
    spec:
      serviceAccountName: go
      shareProcessNamespace: true
      containers:
      - name: go
        imagePullPolicy: Always
        image: 'nginx:latest'
        ports:
          - containerPort: 8080
            protocol: TCP
      - name: datadog-agent
        image: datadog/agent:latest
        ports:
        - containerPort: 8125
          name: dogstatsdport
          protocol: UDP
        - containerPort: 8126
          name: traceport
          protocol: TCP
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: go-secrets
              key: datadog_api_key
        - name: DD_SITE
          value: "datadoghq.com"
        - name: DD_EKS_FARGATE
          value: "true"
        - name: DD_KUBERNETES_KUBELET_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_CLC_RUNNER_ENABLED
          value: "true"
        - name: DD_CLC_RUNNER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DD_ORCHESTRATOR_EXPLORER_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: go-secrets
              key: token
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_LEADER_ELECTION
          value: "true"
        - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_ENABLED
          value: "true" 
        - name: DD_PROCESS_AGENT_ENABLED
          value: "true"
        # namespaceが異なる場合
        - name: DD_CLUSTER_AGENT_URL
          value: "https://datadog-agent-cluster-agent.datadog.svc.cluster.local:5005"
        - name: DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME
          value: "datadog-agent-cluster-agent"
        - name: DD_CLUSTER_NAME
          value: "go-services-prd-cluster"
