kind: Namespace
apiVersion: v1
metadata:
  name: nginx-ymktmk
  labels:
    name: nginx-ymktmk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ymktmk
  namespace: nginx-ymktmk
spec:
  selector:
    matchLabels:
      app: nginx-ymktmk
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ymktmk
    spec:
      containers:
      - name: nginx-ymktmk
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ymktmk
  namespace: nginx-ymktmk
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: nginx-ymktmk
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-ymktmk
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx-ymktmk
