global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'node'
    # scrape_interval: 5s
    static_configs:
      # コンテナ名を指定する
      - targets: ['node_exporter:9100']
  - job_name: 'ec2'
    static_configs:
      - targets:
          - "18.181.227.236:9100"
