service: sns-lambda-ses

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  region: ap-northeast-1
  logRetentionInDays: 14

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: '*'

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  notification:
    name: sns-lambda-ses-${opt:stage}
    handler: bin/email_sender
    events:
      - sns:
          arn: !Ref NotificationTopic
          topicName: sns-lambda-ses-${opt:stage}

resources:
  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: sns-lambda-ses-${opt:stage}
