name: Common CI

description: Make pull requests traceable from GitHub Actions

inputs:
  github-token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Pull Request Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - name: Show URL
      run: echo Pull Request is ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull_request_number }}
      shell: bash

    - name: Adding markdown
      run: echo '### [PR \#${{ steps.pr.outputs.pull_request_number }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull_request_number }})' >> $GITHUB_STEP_SUMMARY
      shell: bash
