apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.0
    # CLBを使用しない場合は、NodePortに変更する
    helm:
      values: |
        service:
          type: NodePort
    chart: gateway
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
