---
# 
# https://istio.io/latest/docs/setup/additional-setup/getting-started/
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gateway-api-crds
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: '-100'
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/kubernetes-sigs/gateway-api.git
#     path: config/crd
#     targetRevision: v0.7.1
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#     syncOptions:
#     - Replace=true
---
# https://istio.io/latest/docs/setup/install/helm/
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.0
    chart: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.0
    chart: istiod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.0
    # CLBを使用しない場合は、NodePortに変更する
    helm:
      values: |
        service:
          type: NodePort
    chart: gateway
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
