apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: presync
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
          - name: AWS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: aws_password
          - name: S3_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: s3_password
          - name: EC2_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: ec2_password
          - name: LAMBDA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: lambda_password
