apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 5.4.11
    helm:
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::009554248005:role/secrets-manager"
      values: |
        aws:
          zoneType: public
        txtOwnerId: my-hostedzone-identifier
    chart: external-dns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
