---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          command: ['sh', '-c', 'echo $AWS_PASSWORD']
          ports:
          - containerPort: 80
          # SecretManager
          env:
          - name: AWS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: aws_password
          # envFrom:
          # - secretRef:
          #     name: env-secrets
      restartPolicy: Never
