---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secret-store
  namespace: presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: external-secret
    creationPolicy: Owner
  data:
  - secretKey: aws_password
    remoteRef:
      key: aws/password

# apiVersion: v1
# kind: Secret
# metadata:
#   name: env-secrets
#   namespace: default
#   annotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
#     argocd.argoproj.io/sync-wave: "1"
# type: Opaque
# data:
#   # base64 encode
#   DB_PASSWORD: dG9tb2tp
