service: msy-zendesk-update

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

functions:
  lambda_handler:
    handler: handler.lambda_handler
    timeout: 10
    environment:
      CLIENT_ID: ${env:CLIENT_ID}
      CLIENT_SECRET: ${env:CLIENT_SECRET}
      USERNAME: ${env:USERNAME}
      PASSWORD: ${env:PASSWORD}

    events:
      - httpApi:
          path: /api/v1/update
          method: post
