apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.29.3
    helm:
      values: |
        fullnameOverride: cluster-autoscaler
        autoDiscovery:
          clusterName: eks
        awsRegion: ap-northeast-1
        cloudProvider: aws
        rbac:
          create: true
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/eks-cluster-autoscaler
    chart: cluster-autoscaler
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
