---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
  namespace: presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
        - name: go-app
          # 仮image
          # image: 009554248005.dkr.ecr.ap-northeast-1.amazonaws.com/go-app:latest
          image: strech/sidekiq-prometheus-exporter
          command: ['sh', '-c', 'echo $AWS_PASSWORD']
          env:
          - name: AWS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: aws_password
          - name: S3_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: s3_password
          - name: EC2_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: ec2_password
          - name: LAMBDA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-secret
                key: lambda_password
          ports:
          - containerPort: 8080
            name: go-app
      restartPolicy: Never

          # envFrom:
          # - secretRef:
          #     name: env-secrets
