apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.7.2
    chart: external-dns
    helm:
      parameters:
        - name: "rbac.serviceAccountAnnotations.eks\\.amazonaws\\.com/role-arn"
          value: "arn:aws:iam::009554248005:role/eks-external-dns"
        - name: "domainFilters[0]"
          value: "code-run.ga"
      values: |
        aws:
          zoneType: public
        txtOwnerId: my-hostedzone-identifier
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
