name: github actions api

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      email:
        description: "email"
        required: true

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: api
        run: |
          echo "name is '${{ github.event.inputs.name }}'"
          echo "email is '${{ github.event.inputs.email }}'"
