# name: cron job

# on:
#   schedule:
#     - cron: '0 0 * * *'

# jobs:
#   cron-job:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Get the last execution time
#           run: |
#             echo Hello Kubernetes !
