# GtihubActionsでkubectlを使う方法
name: db-migration
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/db-migration.yaml"
      - ".github/actions/common/action.yaml"
      - "kubernetes/**"
      - "terraform/**"
  workflow_dispatch:

jobs:
  migation:
    name: migration
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: workflow connect PR
      uses: ./.github/actions/common
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

    # IAM Roleの信頼関係にoidc認証できるように
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::009554248005:role/GitHubActionsOIDC

    - name: Configure EKS
      run: |
        aws eks update-kubeconfig --name eks

    - name: Run db migration
      working-directory: ./test
      run: |
        kubectl apply -f job.yaml

        while true; do
          phase=$(kubectl get pod --selector="job-name=migration" -o 'jsonpath={.items[0].status.phase}')
          if [ "${phase}" != 'Pending' ]; then
            break
          fi
          sleep 2
        done

        while true; do
          is_active=$(kubectl get job migration -o 'jsonpath={.status.active}')
          if [ "${is_active}" != '' ]; then
            sleep 2
            continue
          fi

          succeeded=$(kubectl get job migration -o 'jsonpath={.status.succeeded}')
          if [ "${succeeded}" -eq 1 ]; then
            break
          else
            exit 1
          fi
        done

        kubectl delete -f job.yaml
