name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::009554248005:role/GitHubActions-OIDC

    - name: Install dependencies
      run: yarn install

    - name: Build Next.js app
      run: yarn build

    - name: Upload file to S3
      run: aws s3 cp --recursive --region ap-northeast-1 dist/ s3://online-code

    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/*"

    - name: Deploy
      run: |
        aws s3 sync --region ap-northeast-1 ./out s3://{S3のバケット名} --delete --size-only
        aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id {CloudFrontのid} --paths "/*"
