name: eks-update-job
on:
  push:
    branches:
      - main
jobs: 
  migation:
    name: migration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # role-to-assume: arn:aws:iam::009554248005:role/green-eks-node-group-20220729122253304700000001

    - run: aws sts get-caller-identity

    - name: Configure EKS
      run: |
        aws eks update-kubeconfig --name eks
    
    # AmazonEKS_CNI_Policy AmazonEKSWorkerNodePolicy
    # error: You must be logged in to the server (Unauthorized)
    # 1. IDプロバイダの設定に入力ミスがあった
    # 2. ロールの信頼ポリシーの指定が間違っている。リポジトリ名が正しくないなど
    # 3. SecretsのAWS_ASSUME_ROLE_ARNが正しくない。変数名が違うか、正しいロール名を渡していないなど
    - name: Run kubectl
      run: |
        kubectl get pods -n kube-system
