name: eks-update-job
on:
  push:
    branches:
      - main
jobs: 
  migation:
    name: migration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - run: aws sts get-caller-identity

    - name: Configure EKS
      run: |
        aws eks update-kubeconfig --name eks
        
    - name: Run kubectl
      working-directory: ./test
      run: |
        kubectl apply -f job.yaml

        while true; do
          phase=$(kubectl get pod --selector="job-name=migration" -o 'jsonpath={.items[0].status.phase}')
          if [ "${phase}" != 'Pending' ]; then
            break
          fi
          sleep 2
        done

        while true; do
          is_active=$(kubectl get job migration -o 'jsonpath={.status.active}')
          if [ "${is_active}" != '' ]; then
            sleep 2
            continue
          fi

          succeeded=$(kubectl get job migration -o 'jsonpath={.status.succeeded}')
          if [ "${succeeded}" -eq 1 ]; then
            break
          else
            exit 1
          fi
        done

        kubectl delete -f job.yaml
