name: k6 api, web

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      email:
        description: "email"
        required: true

jobs:
  k6:
    name: k6
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::009554248005:role/GitHubActionsOIDC

    - name: Configure EKS
      run: |
        aws eks update-kubeconfig --name eks

    - name: Apply K6 CRD
      run: |
        kubeclt apply 
        echo "name is '${{ github.event.inputs.name }}'"
    
    # templateファイルへのpath
    # argumentsのオーバーライド機能

  # apply crd
  # delete crd

